# APGO Windows installer. Builds the Wintun client + the shared tray app,
# fetches wintun.dll, installs to %LOCALAPPDATA%\APGO, adds a startup shortcut,
# and launches it. No admin needed to install (the client elevates itself via
# UAC at Connect). Invoked by install.cmd.

$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot   # windows/ -> repo root
Write-Host "=== APGO Windows installer ===" -ForegroundColor Cyan

# TLS 1.2 for older PowerShell/.NET so downloads from go.dev / wintun.net work.
try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocol]::Tls12 } catch {}

# --- prerequisites: auto-install Go if missing or too old -------------------
# The Windows Wintun dependency needs Go >= 1.23.1.
$GoMin    = [version]'1.23.1'
$GoTarget = '1.24.5'

function Get-GoVersion {
    if (-not (Get-Command go -ErrorAction SilentlyContinue)) { return $null }
    try { $v = (& go version) 2>$null } catch { return $null }
    if ($v -match 'go(\d+)\.(\d+)(?:\.(\d+))?') {
        $patch = if ($matches[3]) { $matches[3] } else { '0' }
        return [version]("{0}.{1}.{2}" -f $matches[1], $matches[2], $patch)
    }
    return $null
}

function Install-Go {
    param([string]$Ver)
    $arch = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { 'arm64' } else { 'amd64' }
    $url  = "https://go.dev/dl/go$Ver.windows-$arch.zip"
    $zip  = Join-Path $env:TEMP "go$Ver.zip"
    Write-Host "Downloading Go $Ver ($arch)..."
    Invoke-WebRequest -Uri $url -OutFile $zip
    $dest = Join-Path $env:LOCALAPPDATA 'APGO'
    New-Item -ItemType Directory -Force -Path $dest | Out-Null
    Remove-Item -Recurse -Force (Join-Path $dest 'go') -ErrorAction SilentlyContinue
    Write-Host "Installing Go to $dest\go ..."
    Expand-Archive -Path $zip -DestinationPath $dest -Force   # unpacks to $dest\go
    Remove-Item $zip -ErrorAction SilentlyContinue
    $goBin = Join-Path $dest 'go\bin'
    $env:PATH = "$goBin;$env:PATH"
    # Persist for the user so future runs / the tray app find it too (best-effort).
    try {
        $userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
        if ($userPath -notlike "*$goBin*") {
            [Environment]::SetEnvironmentVariable('Path', "$goBin;$userPath", 'User')
        }
    } catch {}
}

$go = Get-GoVersion
if (-not $go -or $go -lt $GoMin) {
    if ($go) { Write-Host "Found Go $go but need >= $GoMin — installing Go $GoTarget..." }
    else     { Write-Host "Go is not installed — downloading and installing Go $GoTarget..." }
    Install-Go -Ver $GoTarget
    $go = Get-GoVersion
    if (-not $go -or $go -lt $GoMin) { throw "Go install failed or is still too old ($go). Install Go $GoTarget from https://go.dev/dl/ manually and re-run." }
}
Write-Host "Using Go $go"

$install = Join-Path $env:LOCALAPPDATA 'APGO'
$build   = Join-Path $env:TEMP ("apgo-build-" + [guid]::NewGuid().ToString('N').Substring(0,8))
New-Item -ItemType Directory -Force -Path $build | Out-Null

# Stop any running instance and clear the previous session state (fresh install,
# mirroring the macOS installer). The client may be elevated (UAC at Connect), so
# also try an elevated taskkill.
Write-Host "Stopping any running APGO..."
Get-Process -Name 'APGO','overlay-client' -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
try { Start-Process 'taskkill' -ArgumentList '/F','/IM','overlay-client.exe' -Verb RunAs -WindowStyle Hidden -Wait -ErrorAction SilentlyContinue } catch {}
Start-Sleep -Seconds 1

# Fresh session: wipe ~\.apgo so old keys/config/sockets don't linger (avoids
# stale admin keys, node identity, etc.).
$apgoState = Join-Path $env:USERPROFILE '.apgo'
if (Test-Path $apgoState) {
    Write-Host "Clearing previous session state ($apgoState)..."
    Remove-Item -Recurse -Force $apgoState -ErrorAction SilentlyContinue
}

try {
    Write-Host "Building overlay client (Wintun data plane)..."
    Push-Location (Join-Path $repo 'client')
    go mod tidy;  if ($LASTEXITCODE) { throw "client 'go mod tidy' failed" }
    go build -trimpath -o (Join-Path $build 'overlay-client.exe') .
    if ($LASTEXITCODE) { throw "client build failed" }
    Pop-Location

    Write-Host "Building tray app (shared desktop module)..."
    Push-Location (Join-Path $repo 'desktop')
    go mod tidy;  if ($LASTEXITCODE) { throw "desktop 'go mod tidy' failed" }
    # Embed the app icon into the .exe (Explorer / Start menu) via a .syso
    # resource generated by rsrc from windows/app.ico. Best-effort.
    $ico = Join-Path $repo 'windows\app.ico'
    if (Test-Path $ico) {
        go install github.com/akavel/rsrc@latest 2>$null
        $rsrc = Join-Path (go env GOPATH) 'bin\rsrc.exe'
        if (Test-Path $rsrc) {
            & $rsrc -ico $ico -arch amd64 -o (Join-Path $repo 'desktop\rsrc_windows.syso') 2>$null
        } else { Write-Host "  (rsrc not available; skipping exe icon embed)" }
    }
    # -H=windowsgui: no console window for the tray app.
    go build -trimpath -ldflags '-H=windowsgui' -o (Join-Path $build 'APGO.exe') .
    $buildRc = $LASTEXITCODE
    Remove-Item (Join-Path $repo 'desktop\rsrc_windows.syso') -ErrorAction SilentlyContinue
    if ($buildRc) { throw "tray app build failed" }
    Pop-Location

    Write-Host "Fetching wintun.dll..."
    $arch = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64') { 'arm64' } else { 'amd64' }
    $zip  = Join-Path $env:TEMP 'wintun.zip'
    Invoke-WebRequest -Uri 'https://www.wintun.net/builds/wintun-0.14.1.zip' -OutFile $zip
    $wdst = Join-Path $env:TEMP 'wintun-extract'
    Remove-Item -Recurse -Force $wdst -ErrorAction SilentlyContinue
    Expand-Archive -Path $zip -DestinationPath $wdst -Force
    Copy-Item (Join-Path $wdst "wintun\bin\$arch\wintun.dll") (Join-Path $build 'wintun.dll') -Force

    Write-Host "Installing to $install ..."
    Get-Process APGO           -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
    Get-Process overlay-client -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Force -Path $install | Out-Null
    Copy-Item (Join-Path $build 'overlay-client.exe') $install -Force
    Copy-Item (Join-Path $build 'APGO.exe')           $install -Force
    Copy-Item (Join-Path $build 'wintun.dll')         $install -Force

    Write-Host "Adding to startup..."
    $lnk = Join-Path ([Environment]::GetFolderPath('Startup')) 'APGO.lnk'
    $ws  = New-Object -ComObject WScript.Shell
    $sc  = $ws.CreateShortcut($lnk)
    $sc.TargetPath       = Join-Path $install 'APGO.exe'
    $sc.WorkingDirectory = $install
    $sc.Save()

    Write-Host "Launching APGO..."
    Start-Process (Join-Path $install 'APGO.exe')

    Write-Host ""
    Write-Host "Installed to $install. The APGO tray icon should appear." -ForegroundColor Green
    Write-Host "Click it -> Settings (set the same network name/PSK as your other nodes) -> Connect (UAC prompt)."
}
finally {
    Remove-Item -Recurse -Force $build -ErrorAction SilentlyContinue
}
